version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.3
  shellcheck: circleci/shellcheck@3.2

branch-only: &branch-only
  tags:
    ignore: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *branch-only
      - orb-tools/pack:
          filters: *branch-only
      - orb-tools/review:
          orb_name: opifex-ordinis
          filters: *branch-only
      - shellcheck/check:
          filters: *branch-only
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: opifex-ordinis
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *branch-only
